// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGl8oiyk9N7sgp_6fqHxNs22UDEvuroro',
    appId: '1:784234076631:web:39f72b92f6718d3dd61392',
    messagingSenderId: '784234076631',
    projectId: 'todo-unah',
    authDomain: 'todo-unah.firebaseapp.com',
    storageBucket: 'todo-unah.firebasestorage.app',
    measurementId: 'G-ZEFZ1LE5GZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqWv9N6Jv9KvlXQ4N4JeB0RUvII3kmzgs',
    appId: '1:784234076631:android:b8d38d426c765023d61392',
    messagingSenderId: '784234076631',
    projectId: 'todo-unah',
    storageBucket: 'todo-unah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtJGKVocPRUpxwPDpHOGCPEtmHoRK-K0M',
    appId: '1:784234076631:ios:dee4701d806c2f8ed61392',
    messagingSenderId: '784234076631',
    projectId: 'todo-unah',
    storageBucket: 'todo-unah.firebasestorage.app',
    iosBundleId: 'com.example.todoUnah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtJGKVocPRUpxwPDpHOGCPEtmHoRK-K0M',
    appId: '1:784234076631:ios:dee4701d806c2f8ed61392',
    messagingSenderId: '784234076631',
    projectId: 'todo-unah',
    storageBucket: 'todo-unah.firebasestorage.app',
    iosBundleId: 'com.example.todoUnah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGl8oiyk9N7sgp_6fqHxNs22UDEvuroro',
    appId: '1:784234076631:web:2bb34d52944eb1f9d61392',
    messagingSenderId: '784234076631',
    projectId: 'todo-unah',
    authDomain: 'todo-unah.firebaseapp.com',
    storageBucket: 'todo-unah.firebasestorage.app',
    measurementId: 'G-S50S4MK7NS',
  );
}
